# Generated by Django 4.2.6 on 2023-10-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(max_length=255)),
                ('notice_description', models.TextField()),
                ('notice_date', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='noticetbl',
        ),
    ]
