# Generated by Django 4.2.6 on 2023-11-03 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_headmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='headmessage',
            new_name='Head_Master_Message',
        ),
    ]
