# Generated by Django 4.2.6 on 2023-11-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0006_gallery_sliders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_description',
            field=models.ImageField(upload_to=''),
        ),
    ]
