# Generated by Django 4.2.6 on 2023-11-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0007_alter_notice_notice_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='smc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateField()),
            ],
        ),
    ]
