# Generated by Django 4.2.6 on 2023-11-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0008_smc'),
    ]

    operations = [
        migrations.CreateModel(
            name='club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('page', models.CharField(choices=[('1', 'Language'), ('2', 'Debate'), ('3', 'ICT'), ('4', 'Chess'), ('5', 'Math'), ('6', 'Science')], default='SELECT PAGE', max_length=255)),
            ],
        ),
    ]
