# Generated by Django 4.2.6 on 2023-10-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('class_name', models.CharField(max_length=255)),
                ('roll', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=11)),
            ],
        ),
    ]
